GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Subnautica Playguide",
  "author": "Marin",
  "url": "maringuides.com",
  "likes": 16
}